name: Build and push dev image

on:
  push:
    branches:
      - dev
jobs:
  run-github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build image
        run: docker image build -t ing2isimm2024/simplewebdev -f Dockerfile.dev .
      - name: Push image
        run: docker image push ing2isimm2024/simplewebdev


